version: '3.1'

services:

  app:
    container_name: tux_api
    image: tux_api:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - "./app:/app"


  db:
    container_name: tux_db
    restart: always
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD

